---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.microservice.gateways.name }}
  labels:
    name: {{ .Values.microservice.gateways.name }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.microservice.gateways.port }}
    targetPort: {{ .Values.microservice.gateways.port }}
  selector:
    name: {{ .Values.microservice.gateways.name }}