---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.microservice.users.name }}
  labels:
    name: {{ .Values.microservice.users.name }}
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: {{ .Values.microservice.users.port }}
    nodePort: 30001
  selector:
    name: {{ .Values.microservice.users.name }}